version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - php:
  fixme:
    enabled: false
  phpmd:
    enabled: false
  phan:
    enabled: true
    config:
        file_extensions: "php"
        ignore-undeclared: false
        quick: false
        backward-compatibility-checks: false
        dead-code-detection: true
        directory_list: "src/"
exclude_patterns:
- "config/"
- "view/"
