sudo: false

language: php

php:
  - 7
  - hhvm

matrix:
  exclude:
    - php: hhvm
  allow_failures:
    - php: hhvm
    
before_script:
  - composer selfupdate
  - composer create-project mvc5/mvc5-application build --stability dev --keep-vcs

after_script:
  - composer require codeclimate/php-test-reporter
  - CODECLIMATE_REPO_TOKEN="91a269c5223b953a05b77fb6ac0c41c308f3caffcdff350af60f804960242991" vendor/bin/test-reporter --coverage-report build/logs/clover.xml --stdout > build/logs/codeclimate.json
  - "curl -X POST -d @build/logs/codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/coverage.clover

script:
  - php -d date.timezone=America/Chicago opcache.enable=1 -d opcache.enable_cli=1 build/public/index.php >/dev/null
  - php -d date.timezone=America/Chicago opcache.enable=0 -d opcache.enable_cli=0 build/public/index.php >/dev/null
  - php -n build/public/index.php >/dev/null
  - phpunit --configuration build/phpunit.xml --coverage-clover build/logs/clover.xml
  - phpunit --configuration build/phpunit.xml --coverage-clover build/logs/coverage.clover

notifications:
  email: false
